export const FETCH_LANDING_DATA_REQUEST = "FETCH_LANDING_DATA_REQUEST";
export const FETCH_LANDING_DATA_SUCCESS = "FETCH_LANDING_DATA_SUCCESS";
export const FETCH_LANDING_DATA_ERROR = "FETCH_LANDING_DATA_ERROR";

export const FETCH_LANDING_DATA_DETAIL_REQUEST =
	"FETCH_LANDING_DATA_DETAIL_REQUEST";
export const FETCH_LANDING_DATA_DETAIL_SUCCESS =
	"FETCH_LANDING_DATA_DETAIL_SUCCESS";
export const FETCH_LANDING_DATA_DETAIL_ERROR =
	"FETCH_LANDING_DATA_DETAIL_ERROR";
